=== JanReichelt/Jans-Repo/projects/2019/klausur/cs2013_4_sax/buecher.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT buecher (buch)+>
<!ELEMENT buch (titel,isbn,autor+,verlag*)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT verlag (#PCDATA)>

=== JanReichelt/Jans-Repo/projects/2019/klausur/cs2013_4_sax/buecher_non-valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buecher SYSTEM "buecher.dtd">
<buecher>
    <buch>
        <titel>Java - Der Code</titel>
        <isbn>3-8266-1462-3</isbn>
    </buch>
    <buch>
        <titel>XSLT und XPath</titel>
        <isbn>3-8266-1532-8</isbn>
        <autor>Marco Skulschus</autor>
        <autor>Marcus Wiederstein</autor>
    </buch>
    <buch>
        <titel>XSL-FO</titel>
        <isbn>3-8266-1531-3</isbn>
        <autor>Marco Skulschus</autor>
        <autor>Marcus Wiederstein</autor>
    </buch>
</buecher>
